services:
  mongo-product:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo-product
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "admin"
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin@mongo-product:27017/"
  product-service:
    build:
      context: ..
      dockerfile: product.Dockerfile
    image: product-service
    env_file:
      - env/product.env
    ports:
      - "8080:8080"
    depends_on:
      - mongo-product
    profiles:
      - app
