services:
  postgres-user:
    image: postgres
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pwd
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"