spring:
  r2dbc:
    name: "${POSTGRES_DB:user}"
    username: "${POSTGRES_USER:user_user}"
    password: "${POSTGRES_PWD:user_pwd}"
    url: "r2dbc:postgresql://${POSTGRES_URL:localhost}:${POSTGRES_PORT:5432}"
