services:
  product:
    url: "http://localhost:8081"
  user:
    url: "http://localhost:8082"

spring:
  datasource:
    username: "${POSTGRES_USER:order_user}"
    password: "${POSTGRES_PWD:order_pwd}"
    url: "jdbc:postgresql://${POSTGRES_URL:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:order_db}"
