spring:
  data:
    mongodb:
      database: "${MONGO_DB:product_db}"
      port: "${MONGO_PORT:27017}"
      host: "${MONGO_HOST:localhost}"
      password: "${MONGO_PWD:product_pwd}"
      username: "${MONGO_USER:product_user}"
server:
  port: 8081