services:
  postgres-user:
    image: postgres
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pwd
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"